In [1]:
import sqlite3
import pandas as pd

In [ ]:
pandas.read_csv(csvfile.to_sql('table_1', conn, if_exists='append', index=False)

In [6]:
def create_connection(db_file):
    """ create a database connection to a SQLite database """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
    finally:
        if conn:
            conn.close()


if __name__ == '__main__':
    create_connection("sqlite/db/pythonsqlite.db")

2.6.0

In [11]:
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        return conn
    except Error as e:
        print(e)

    return conn

In [12]:
def create_table(conn, create_table_sql):
    """ create a table from the create_table_sql statement
    :param conn: Connection object
    :param create_table_sql: a CREATE TABLE statement
    :return:
    """
    try:
        c = conn.cursor()
        c.execute(create_table_sql)
    except Error as e:
        print(e)

In [13]:
def main():
    database = "sqlite/db/pythonsqlite.db"

    sql_create_food_prices_table = """CREATE TABLE IF NOT EXISTS food_prices (
                                    id integer PRIMARY KEY,
                                    cm_name text NOT NULL,
                                    adm0_name text NOT NULL,
                                    um_name text NOT NULL,
                                    mp_year text NOT NULL,
                                    mp_price integer NOT NULL
                                );"""

    # create a database connection
    conn = create_connection(database)

    # create tables
    if conn is not None:
        # create food_prices table
        create_table(conn, sql_create_food_prices_table)

    else:
        print("Error! cannot create the database connection.")

In [14]:
if __name__ == '__main__':
    main()

In [2]:
con = sqlite3.connect("sqlite/db/pythonsqlite.db")

In [24]:
df1 = pd.read_csv('wfpvam_foodprices.csv')

In [26]:
df1 = df1[['cm_name', 'adm0_name', 'um_name', 'mp_year', 'mp_price']]

In [27]:
df1

,cm_name,adm0_name,um_name,mp_year,mp_price
0,Bread - Retail,Afghanistan,KG,2014,50.00
1,Bread - Retail,Afghanistan,KG,2014,50.00
2,Bread - Retail,Afghanistan,KG,2014,50.00
3,Bread - Retail,Afghanistan,KG,2014,50.00
4,Bread - Retail,Afghanistan,KG,2014,50.00
...,...,...,...,...,...
1764351,"Sugar (white, fortified) - Retail",Zimbabwe,KG,2017,1.50
1764352,Beans - Retail,Zimbabwe,KG,2018,2.80
1764353,Maize - Retail,Zimbabwe,KG,2018,0.40
1764354,Oil (vegetable) - Retail,Zimbabwe,L,2018,2.35
1764355,"Maize meal (white, roller) - Retail",Zimbabwe,KG,2018,0.55

In [23]:
# df.to_sql('food_prices', con, if_exists='replace', index=False)

In [64]:
con = sqlite3.connect("sqlite/db/pythonsqlite.db")

In [65]:
df = pd.read_sql_query("SELECT * from food_prices", con)

In [66]:
df

,cm_name,adm0_name,um_name,mp_year,mp_price
0,Bread - Retail,Afghanistan,KG,2014,50.00
1,Bread - Retail,Afghanistan,KG,2014,50.00
2,Bread - Retail,Afghanistan,KG,2014,50.00
3,Bread - Retail,Afghanistan,KG,2014,50.00
4,Bread - Retail,Afghanistan,KG,2014,50.00
...,...,...,...,...,...
1311188,Wheat flour (fortified) - Retail,Zimbabwe,KG,2017,1.50
1311189,"Sugar (white, fortified) - Retail",Zimbabwe,KG,2017,1.50
1311190,Beans - Retail,Zimbabwe,KG,2018,2.80
1311191,Maize - Retail,Zimbabwe,KG,2018,0.40
1311192,"Maize meal (white, roller) - Retail",Zimbabwe,KG,2018,0.55

In [74]:
df.columns

Index(['cm_name', 'adm0_name', 'um_name', 'mp_year', 'mp_price'], dtype='object')

In [63]:
df = df.loc[df['um_name'] == 'KG']

In [67]:
df['cm_name'].value_counts()[:5].index.tolist()

['Millet - Retail',
 'Rice (imported) - Retail',
 'Maize - Retail',
 'Sorghum - Retail',
 'Wheat flour - Retail']

In [70]:
mask = df['cm_name'].isin(df['cm_name'].value_counts()[:5].index.tolist())

In [72]:
df.loc[mask]

                      cm_name    adm0_name um_name  mp_year  mp_price
2425     Wheat flour - Retail  Afghanistan      KG     2000     10.06
2426     Wheat flour - Retail  Afghanistan      KG     2000      9.88
2427     Wheat flour - Retail  Afghanistan      KG     2000     10.23
2428     Wheat flour - Retail  Afghanistan      KG     2000     13.90
2429     Wheat flour - Retail  Afghanistan      KG     2000     12.69
...                       ...          ...     ...      ...       ...
1311178        Maize - Retail     Zimbabwe      KG     2018      0.29
1311182        Maize - Retail     Zimbabwe      KG     2017      0.23
1311183      Sorghum - Retail     Zimbabwe      KG     2017      0.17
1311184       Millet - Retail     Zimbabwe      KG     2017      0.17
1311191        Maize - Retail     Zimbabwe      KG     2018      0.40

[220287 rows x 5 columns]

In [73]:
pip list

Package                       Version
----------------------------- -------------------
anyio                         2.0.2
argon2-cffi                   20.1.0
asgiref                       3.2.10
async-generator               1.10
attrs                         20.3.0
Automat                       20.2.0
Babel                         2.9.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.1
bleach                        3.2.1
bokeh                         2.2.3
brotlipy                      0.7.0
certifi                       2020.12.5
cffi                          1.14.4
chardet                       4.0.0
colorcet                      2.0.6
constantly                    15.1.0
cryptography                  3.3.1
cycler                        0.10.0
decorator                     4.4.2
defusedxml                    0.6.0
Django                        3.1.2
entrypoints                   0.3
holoviews                     1.14.1
hyperlink                     21.0.0
idna                          2.10
importlib-metadata            3.4.0
incremental                   17.5.0
ipykernel                     5.4.2
ipython                       7.19.0
ipython-genutils              0.2.0
jedi                          0.18.0
Jinja2                        2.11.2
json5                         0.9.5
jsonschema                    3.2.0
jupyter-client                6.1.11
jupyter-core                  4.7.0
jupyter-server                1.2.1
jupyterlab                    3.0.3
jupyterlab-pygments           0.1.2
jupyterlab-server             2.1.1
kiwisolver                    1.3.1
Markdown                      3.3.3
MarkupSafe                    1.1.1
matplotlib                    3.3.2
mistune                       0.8.4
nbclassic                     0.2.6
nbclient                      0.5.1
nbconvert                     6.0.7
nbformat                      5.0.8
nest-asyncio                  1.4.3
notebook                      6.1.6
numpy                         1.19.2
olefile                       0.46
packaging                     20.8
pandas                        1.2.0
pandocfilters                 1.4.2
panel                         0.10.3
param                         1.10.1
parso                         0.8.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.1.0
pip                           20.3.3
prometheus-client             0.9.0
prompt-toolkit                3.0.10
psycopg2                      2.8.5
ptyprocess                    0.7.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycparser                     2.20
pyct                          0.4.6
Pygments                      2.7.3
PyHamcrest                    2.0.2
pyOpenSSL                     20.0.1
pyparsing                     2.4.7
pyrsistent                    0.17.3
PySocks                       1.7.1
python-dateutil               2.8.1
pytz                          2020.5
pyviz-comms                   2.0.1
PyYAML                        5.3.1
pyzmq                         20.0.0
requests                      2.25.1
Send2Trash                    1.5.0
setuptools                    49.6.0.post20210108
six                           1.15.0
sniffio                       1.2.0
sqlparse                      0.4.1
terminado                     0.9.2
testpath                      0.4.4
tornado                       6.1
tqdm                          4.56.0
traitlets                     5.0.5
txaio                         20.12.1
typing-extensions             3.7.4.3
urllib3                       1.26.2
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.36.2
zipp                          3.4.0
zope.interface                5.2.0
Note: you may need to restart the kernel to use updated packages.

In [59]:
df

         cm_name    adm0_name um_name  mp_year  mp_price
0            NaN  Afghanistan      KG     2014     50.00
1            NaN  Afghanistan      KG     2014     50.00
2            NaN  Afghanistan      KG     2014     50.00
3            NaN  Afghanistan      KG     2014     50.00
4            NaN  Afghanistan      KG     2014     50.00
...          ...          ...     ...      ...       ...
1311188      NaN     Zimbabwe      KG     2017      1.50
1311189      NaN     Zimbabwe      KG     2017      1.50
1311190      NaN     Zimbabwe      KG     2018      2.80
1311191      NaN     Zimbabwe      KG     2018      0.40
1311192      NaN     Zimbabwe      KG     2018      0.55

[1311193 rows x 5 columns]

In [42]:
t = df.loc[df['mp_year'] == 2020]

In [43]:
t

,cm_name,adm0_name,um_name,mp_year,mp_price
69,Bread - Retail,Afghanistan,KG,2020,50.000
70,Bread - Retail,Afghanistan,KG,2020,50.000
71,Bread - Retail,Afghanistan,KG,2020,50.000
72,Bread - Retail,Afghanistan,KG,2020,50.000
275,Wheat - Retail,Afghanistan,KG,2020,25.375
...,...,...,...,...,...
1307709,"Maize meal (white, breakfast) - Retail",Zambia,KG,2020,5.310
1307710,"Maize meal (white, breakfast) - Retail",Zambia,KG,2020,5.310
1307711,"Maize meal (white, breakfast) - Retail",Zambia,KG,2020,5.120
1307712,"Maize meal (white, breakfast) - Retail",Zambia,KG,2020,1.870
1307713,"Maize meal (white, breakfast) - Retail",Zambia,KG,2020,5.160

In [44]:
t = t.loc[t['cm_name'] == 'Bread - Retail']

In [46]:
t = t.sort_values('mp_price')

In [47]:
t

                cm_name           adm0_name um_name  mp_year  mp_price
1094667  Bread - Retail  State of Palestine      KG     2020      2.30
1094665  Bread - Retail  State of Palestine      KG     2020      2.30
1094666  Bread - Retail  State of Palestine      KG     2020      2.30
1094668  Bread - Retail  State of Palestine      KG     2020      2.30
1094660  Bread - Retail  State of Palestine      KG     2020      2.33
...                 ...                 ...     ...      ...       ...
311553   Bread - Retail               Congo      KG     2020   1183.00
310826   Bread - Retail               Congo      KG     2020   1188.00
311551   Bread - Retail               Congo      KG     2020   1192.00
310134   Bread - Retail               Congo      KG     2020   1194.00
311549   Bread - Retail               Congo      KG     2020   1271.00

[718 rows x 5 columns]

In [48]:
t = t.drop_duplicates(subset=['adm0_name'], keep='first')

In [49]:
t

                cm_name           adm0_name um_name  mp_year  mp_price
1094667  Bread - Retail  State of Palestine      KG     2020      2.30
853662   Bread - Retail                Peru      KG     2020      6.78
376061   Bread - Retail              Gambia      KG     2020     14.00
2413     Bread - Retail         Afghanistan      KG     2020     29.41
520333   Bread - Retail          Kyrgyzstan      KG     2020     43.98
9392     Bread - Retail           Argentina      KG     2020    111.25
312249   Bread - Retail               Congo      KG     2020    760.00

In [50]:
t = t.nsmallest(5, ['mp_price'])

In [ ]:
'Bread - Retail'

In [22]:
df

,cm_name,adm0_name,um_name,mp_year,mp_price
0,Bread - Retail,Afghanistan,KG,2014,50.00
1,Bread - Retail,Afghanistan,KG,2014,50.00
2,Bread - Retail,Afghanistan,KG,2014,50.00
3,Bread - Retail,Afghanistan,KG,2014,50.00
4,Bread - Retail,Afghanistan,KG,2014,50.00
...,...,...,...,...,...
1764350,Wheat flour (fortified) - Retail,Zimbabwe,KG,2017,1.50
1764351,"Sugar (white, fortified) - Retail",Zimbabwe,KG,2017,1.50
1764352,Beans - Retail,Zimbabwe,KG,2018,2.80
1764353,Maize - Retail,Zimbabwe,KG,2018,0.40
1764355,"Maize meal (white, roller) - Retail",Zimbabwe,KG,2018,0.55

In [20]:
len(a['cm_name'].unique())

625

In [6]:
a = df['um_name'].unique()

In [7]:
a

array(['KG', 'Day', 'Unit', 'L', 'USD/LCU', '30 pcs', '500 G', '125 G',
       'Packet', '900 G', '50 Pounds', '100 KG', '46 KG', '11.5 KG',
       'Pound', 'Cuartilla', 'Libra', '5 L', '10 pcs', '90 KG', '1.5 L',
       '400 G', 'Sack', 'Package', 'Head', 'MT', '85 G', 'Gallon',
       '380 G', '500 ML', 'Month', 'Course', '50 KG', '100 Pounds',
       '168 G', '45 KG', '70 G', '200 G', '68 KG', '109 KG', '91 KG',
       '93 KG', '10 KG', 'Bunch', '250 KG', '100 Tubers', '73 KG',
       '84 KG', '52 KG', '27 KG', '20 KG', '16 KG', '650 G', '750 ML',
       '115 G', '360 pcs', '50 pcs', '100 pcs', 'Marmite', '350 G',
       '385 G', '1.8 KG', 'Cylinder', '4 pcs', '150 ml', '5 KG', '2 KG',
       '1.8 L', '170 G', '1.5 KG', '300 G', '0.8 KG', '160 G', '750 G',
       '12.5 KG', '200 ML', '150 G', '20 L', '1.3 KG', '185 G', 'Loaf',
       '2.25 KG', '5 pcs', '250 G', '11 KG', 'Brush', '100 ML', 'Bar',
       '250 ML', 'Heap', '1.6 KG', 'Dozen', '100 L', '1.4 KG', '20 G',
       '3.4 KG', '0.5 KG', '1.1 KG', '2.1 KG', '1.2 KG', '3.1 KG',
       '3.5 KG', 'Bundle', 'LCU/3.5kg', '25 KG', '3 L', 'Cubic meter',
       '60 KG', '3 KG', '2.5 KG', '700 G', '800 G', '28 pcs', '900 ML',
       '1 piece', '50 ML', 'Pair', '1 GB', '12 KG', 'kWh', '18 KG'],
      dtype=object)

In [9]:
list(df['cm_name'].unique())

['Bread - Retail',
 'Wheat - Retail',
 'Rice (low quality) - Retail',
 'Oil (cooking) - Retail',
 'Sugar - Retail',
 'Pulses - Retail',
 'Wheat flour (high quality) - Retail',
 'Salt - Retail',
 'Rice (high quality) - Retail',
 'Wheat flour (low quality) - Retail',
 'Wheat flour - Retail',
 'Rice - Retail',
 'Beans (white) - Retail',
 'Potatoes - Retail',
 'Meat (chicken) - Retail',
 'Lentils - Retail',
 'Tomatoes - Retail',
 'Meat (beef) - Retail',
 'Carrots - Retail',
 'Onions - Retail',
 'Bananas - Retail',
 'Tea - Retail',
 'Apples - Retail',
 'Oranges - Retail',
 'Meat (camel) - Retail',
 'Cassava flour - Retail',
 'Salt (iodised) - Retail',
 'Sugar (white) - Retail',
 'Rice (white, imported) - Retail',
 'Maize meal (yellow) - Retail',
 'Fish (mackerel, dry) - Retail',
 'Beans (kidney, pinto) - Retail',
 'Wheat flour - Wholesale',
 'Wheat - Wholesale',
 'Rice (white) - Retail',
 'Maize (yellow) - Wholesale',
 'Beans - Retail',
 'Pasta - Retail',
 'Meat (pork) - Retail',
 'Cheese (dry) - Retail',
 'Peas (split, dry) - Retail',
 'Cabbage - Retail',
 'Apples (red) - Retail',
 'Cucumbers (greenhouse) - Retail',
 'Tomatoes (paste) - Retail',
 'Beetroots - Retail',
 'Fish (fresh) - Retail',
 'Bread (high grade flour) - Retail',
 'Bread (first grade flour) - Retail',
 'Buckwheat - Retail',
 'Rice (coarse) - Retail',
 'Lentils (masur) - Retail',
 'Rice (medium grain) - Retail',
 'Rice (coarse, BR-8/ 11/, Guti Sharna) - Retail',
 'Rice (coarse, Guti Sharna) - Retail',
 'Oil (palm) - Retail',
 'Tea (black) - Retail',
 'Oil (sunflower) - Retail',
 'Oil (mustard) - Retail',
 'Oil (groundnut) - Retail',
 'Oil (soybean) - Retail',
 'Lentils (moong) - Retail',
 'Sugar (jaggery/gur) - Retail',
 'Lentils (urad) - Retail',
 'Ghee (vanaspati) - Retail',
 'Chickpeas - Retail',
 'Maize - Wholesale',
 'Rice (imported) - Wholesale',
 'Rice (imported) - Retail',
 'Sorghum - Wholesale',
 'Sorghum - Retail',
 'Maize (white) - Retail',
 'Rice (local) - Retail',
 'Millet - Wholesale',
 'Millet - Retail',
 'Sweet potatoes - Retail',
 'Yam - Retail',
 'Plantains - Retail',
 'Peas (green, dry) - Retail',
 'Soybeans - Retail',
 'Sorghum (red) - Retail',
 'Cassava (cossette) - Retail',
 'Lemons - Retail',
 'Wheat flour (imported) - Retail',
 'Cassava meal (gari) - Retail',
 'Fish (tilapia) - Retail',
 'Papaya - Retail',
 'Okra (fresh) - Retail',
 'Groundnuts (Bambara) - Retail',
 'Peppers (red, dry) - Retail',
 'Groundnuts (small, unshelled) - Retail',
 'Cassava meal (tapioca) - Retail',
 'Coconut (dried) - Retail',
 'Yam (white) - Retail',
 'Fish (fresh, silvi) - Retail',
 'Oil (palm nut) - Retail',
 'Cassava meal (gari, fine) - Retail',
 'Yam (dry) - Retail',
 'Yam (flour) - Retail',
 'Beans (red) - Retail',
 'Beans (black) - Retail',
 'Rice (paddy) - Retail',
 'Cassava (fresh) - Retail',
 'Yam (yellow) - Retail',
 'Leafy vegetables - Retail',
 'Maize - Retail',
 'Shrimps - Retail',
 'Taro - Retail',
 'Snail - Retail',
 'Rice (imported, Indian) - Retail',
 'Rice (red) - Retail',
 'Meat (beef, chops with bones) - Retail',
 'Meat (chicken, whole) - Retail',
 'Noodles (short) - Retail',
 'Potatoes (Irish, imilla) - Retail',
 'Rice (estaquilla) - Retail',
 'Rice (carolina 2da) - Retail',
 'Potatoes (black) - Retail',
 'Rice (long grain) - Retail',
 'Rice (Grano de Oro) - Retail',
 'Rice (good quality) - Retail',
 'Bread (wheat) - Retail',
 'Rice (carolina, 1st) - Retail',
 'Groundnuts (unshelled) - Retail',
 'Beans (niebe) - Retail',
 'Sorghum (white) - Retail',
 'Groundnuts (shelled) - Retail',
 'Rice - Wholesale',
 'Beans (niebe) - Wholesale',
 'Maize flour - Retail',
 'Oil (vegetable) - Retail',
 'Potatoes (Irish) - Retail',
 'Rice (high quality, local) - Retail',
 'Rice (low quality, local) - Retail',
 'Meat (goat) - Retail',
 'Avocados - Retail',
 'Fish (lates,dry,local) - Retail',
 'Fish (lates,dry,imported) - Retail',
 'Rice (imported, Tanzanian) - Retail',
 'Rice (mixed, low quality) - Wholesale',
 'Soybeans - Wholesale',
 'Rice (mixed, low quality) - Retail',
 'Fish (snake head) - Wholesale',
 'Fish (snake head) - Retail',
 'Fish (catfish) - Wholesale',
 'Fish (catfish) - Retail',
 'Meat (pork, with fat) - Wholesale',
 'Meat (pork, with fat) - Retail',
 'Salt (iodised) - Wholesale',
 'Eggplants - Wholesale',
 'Eggplants - Retail',
 'Snake gourd - Wholesale',
 'Snake gourd - Retail',
 'Cabbage (chinese, flowering) - Wholesale',
 'Cabbage (chinese, flowering) - Retail',
 'Fish (snake head, dry) - Wholesale',
 'Fish (snake head, dry) - Retail',
 'Beans (yardlong, green) - Wholesale',
 'Beans (yardlong, green) - Retail',
 'Water spinach - Wholesale',
 'Water spinach - Retail',
 'Fish (striped catfish) - Wholesale',
 'Fish (striped catfish) - Retail',
 'Wax gourd - Wholesale',
 'Wax gourd - Retail',
 'Prawn - Wholesale',
 'Fish (dry) - Retail',
 'Rice (long grain, imported) - Retail',
 'Milk (powder) - Retail',
 'Fish (frozen) - Retail',
 'Cocoyam (macabo) - Retail',
 'Cassava - Retail',
 'Maize (local) - Retail',
 'Maize (yellow) - Retail',
 'Maize (imported) - Retail',
 'Sesame - Retail',
 'Squashes - Retail',
 'Fuel (gas) - Retail',
 'Meat (chicken, frozen) - Retail',
 'Rice (broken, imported) - Retail',
 'Fish - Retail',
 'Groundnuts - Retail',
 'Chicken - Retail',
 'Fish (smoked) - Retail',
 'Beans (green, fresh) - Retail',
 'Meat (antelope, smoked) - Retail',
 'Meat (gazelle, smoked) - Retail',
 'Peanut - Retail',
 'Sorghum (berbere) - Retail',
 'Rice (Indica) - Wholesale',
 'Rice (Japonica) - Wholesale',
 'Wheat flour (first grade) - Wholesale',
 'Maize (local) - Wholesale',
 'Maize (white) - Wholesale',
 'Beans (red) - Wholesale',
 'Potatoes - Wholesale',
 'Meat (chicken) - Wholesale',
 'Sugar - Wholesale',
 'Garlic - Wholesale',
 'Onions (red) - Wholesale',
 'Onions (white) - Wholesale',
 'Pasta - Wholesale',
 'Tomatoes - Wholesale',
 'Meat (pork) - Wholesale',
 'Meat (beef) - Wholesale',
 'Potatoes (black) - Wholesale',
 'Plantains - Wholesale',
 'Coffee - Wholesale',
 'Carrots - Wholesale',
 'Cabbage - Wholesale',
 'Oil (sunflower) - Wholesale',
 'Salt - Wholesale',
 'Rice (ordinary, first quality) - Wholesale',
 'Chickpeas (imported) - Wholesale',
 'Meat (beef, minced) - Wholesale',
 'Peas (green, dry) - Wholesale',
 'Sugar (brown) - Wholesale',
 'Sugar (brown, loaf) - Wholesale',
 'Cauliflower - Wholesale',
 'Cucumbers (greenhouse) - Wholesale',
 'Milk (powder) - Wholesale',
 'Oranges (big size) - Wholesale',
 'Rice (high quality) - Wholesale',
 'Bananas - Wholesale',
 'Beans (red, fresh) - Wholesale',
 'Cassava (dry) - Wholesale',
 'Cheese (local) - Wholesale',
 'Lemons - Wholesale',
 'Fish (sardine, canned) - Wholesale',
 'Fish (tuna, canned) - Wholesale',
 'Onions (local) - Wholesale',
 'Tomatoes (local) - Wholesale',
 'Oranges - Wholesale',
 'Beetroots - Wholesale',
 'Spinach - Wholesale',
 'Beans (string) - Wholesale',
 'Papaya - Wholesale',
 'Blackberry - Wholesale',
 'Broccoli - Wholesale',
 'Mangoes - Wholesale',
 'Pumpkin - Wholesale',
 'Tomatoes (dried) - Wholesale',
 'Cheese - Wholesale',
 'Lentils (imported) - Wholesale',
 'Peas (fresh) - Wholesale',
 'Fish (frozen) - Wholesale',
 'Peppers (red) - Wholesale',
 'Meat (chicken, whole, frozen) - Wholesale',
 'Beans (cranberry) - Wholesale',
 'Maize flour - Wholesale',
 'Wheat flour (local) - Wholesale',
 'Rice (ordinary, second quality) - Wholesale',
 'Potatoes (unica) - Wholesale',
 'Sugar (white) - Wholesale',
 'Beans (green, fresh) - Wholesale',
 'Beans (black, imported) - Wholesale',
 'Cassava - Wholesale',
 'Fish (tilapia) - Wholesale',
 'Passion fruit - Wholesale',
 'Yam - Wholesale',
 'Guava - Wholesale',
 'Fish (dry) - Wholesale',
 'Apples (red) - Wholesale',
 'Barley - Wholesale',
 'Fish (salted) - Retail',
 'Groundnuts (paste) - Retail',
 'Cassava meal (foufou) - Retail',
 'Rice (denikassia, imported) - Retail',
 'Yam (florido) - Retail',
 'Cashew nut - Retail',
 'Cornstarch - Retail',
 'Fish (appolo) - Retail',
 'Cotton - Retail',
 'Cassava meal (attieke) - Retail',
 'Cocoa - Retail',
 'Coffee - Retail',
 'Maize meal - Retail',
 'Meat (goat, with bones) - Retail',
 'Cassava (chikwangue) - Retail',
 'Maize meal (imported) - Retail',
 'Maize flour (imported) - Retail',
 'Cowpeas - Retail',
 'Rice (long grain) - Wholesale',
 'Beans (white) - Wholesale',
 'Lentils - Wholesale',
 'Noodles (short) - Wholesale',
 'Rice (white) - Wholesale',
 'Peanut - Wholesale',
 'Oil (vegetable, local) - Wholesale',
 'Tomatoes (greenhouse) - Wholesale',
 'Lettuce - Wholesale',
 'Apples - Wholesale',
 'Rice (short grain, low quality, local) - Wholesale',
 'Cucumbers - Wholesale',
 'Maize (white, dry) - Wholesale',
 'Avocados - Wholesale',
 'Onions (white, dry) - Wholesale',
 'Pineapples - Wholesale',
 'Peppers (fresh) - Wholesale',
 'Watermelons - Wholesale',
 'Oat flakes - Wholesale',
 'Beans (pod) - Wholesale',
 'Onions (red, dry) - Wholesale',
 'Potatoes (super chola) - Wholesale',
 'Strawberries - Wholesale',
 'Melons (cantaloupe) - Wholesale',
 'Naranjilla (hybrid) - Wholesale',
 'Plantains (barraganete, mature) - Wholesale',
 'Plantains (barraganete, green) - Wholesale',
 'Plantains (dominico, mature) - Wholesale',
 'Plantains (dominico, green) - Wholesale',
 'Tree tomatoes - Wholesale',
 'Grapes (black) - Wholesale',
 'Grapes (pink) - Wholesale',
 'Oil (cooking) - Wholesale',
 'Beans (dry) - Wholesale',
 'Garlic - Retail',
 'Ghee (artificial) - Retail',
 'Ghee (natural) - Retail',
 'Onions (red) - Retail',
 'Onions (white) - Retail',
 'Beans (fava, dry) - Retail',
 'Cheese - Retail',
 'Meat (beef, without bones) - Retail',
 'Wheat (white) - Retail',
 'Teff (Sergegna) - Retail',
 'Pasta (macaroni) - Retail',
 'Butter (cow milk) - Retail',
 'Butter (goat milk) - Retail',
 'Meat - Retail',
 'Peppers (green) - Retail',
 'Lettuce - Retail',
 'Guava - Retail',
 'Mangoes - Retail',
 'Kale - Retail',
 'Swiss chard - Retail',
 'Honey - Retail',
 'Corn Soy Blend (CSB++, food aid) - Retail',
 'Beans (haricot) - Retail',
 'Wheat (food aid) - Retail',
 'Kocho - Retail',
 'Pasta (spaghetti) - Retail',
 'Milk - Retail',
 'Fonio - Retail',
 'Rice (paddy, long grain, local) - Retail',
 'Rice (basmati, broken) - Retail',
 'Fish (bonga) - Retail',
 'Meat (mutton) - Retail',
 'Coffee (instant) - Retail',
 'Rice (medium grain, imported) - Retail',
 'Rice (small grain, imported) - Retail',
 'Oranges (big size) - Retail',
 'Beans (dry) - Retail',
 'Dates - Retail',
 'Butter - Retail',
 'Cucumbers - Retail',
 'Pumpkin - Retail',
 'Cassava leaves - Retail',
 'Meat (sheep) - Retail',
 'Peppers (red) - Retail',
 'Peppers (fresh) - Retail',
 'Watermelons - Retail',
 'Gari - Retail',
 'Plantains (apentu) - Retail',
 'Tomatoes (local) - Retail',
 'Plantains (apem) - Retail',
 'Tomatoes (navrongo) - Retail',
 'Peppers (dried) - Retail',
 'Yam (puna) - Retail',
 'Fish (mackerel, fresh) - Retail',
 'Onions (imported) - Retail',
 'Chili (red, dry raw) - Retail',
 'Beans (niebe, white) - Retail',
 'Onions (local) - Retail',
 'Meat (beef, second quality) - Retail',
 'Meat (chicken, frozen, imported) - Retail',
 'Charcoal - Retail',
 'Fish (goldstripe sardinella) - Retail',
 'Bananas (local) - Retail',
 'Fish (barbel, sole) - Retail',
 'Fish (mullet, catfish) - Retail',
 'Meat (sheep, second quality) - Retail',
 'Meat (pork, first quality) - Retail',
 'Meat (pork, second quality) - Retail',
 'Bananas (imported) - Retail',
 'Meat (chicken, broiler) - Retail',
 'Chili (red) - Retail',
 'Eggs - Retail',
 "Chili (bird's eye) - Retail",
 'Onions (shallot) - Retail',
 "Chili (bird's eye, green) - Retail",
 'Chili (red, curly) - Retail',
 'Eggs (broiler) - Retail',
 'Garlic (medium) - Retail',
 'Rice (medium quality) - Retail',
 'Sugar (local) - Retail',
 'Sugar (premium) - Retail',
 'Oil (vegetable, bulk) - Retail',
 'Oil (vegetable, packaged) - Retail',
 'Onions (shallot, medium) - Retail',
 'Meat (beef, first quality) - Retail',
 'Chili (red, large) - Retail',
 "Chili (bird's eye, red) - Retail",
 'Bulgur - Retail',
 'Cheese (local) - Retail',
 'Meat (lamb) - Retail',
 'Handwash soap - Retail',
 'Bread (khoboz) - Retail',
 'Rice (glutinous, unmilled) - Retail',
 'Radish - Retail',
 'Oil (olive) - Retail',
 'Cheese (picon) - Retail',
 'Bread (pita) - Retail',
 'Cheese (white, boiled) - Retail',
 'Spinach - Retail',
 'Wheat flour (first grade) - Retail',
 'Beans - Wholesale',
 'Cooking fat - Retail',
 'Buckwheat grits - Retail',
 'Semolina - Retail',
 'Cheese (fat) - Retail',
 'Cheese (low-fat) - Retail',
 'Apples (dried) - Retail',
 'Walnuts - Retail',
 'Peas - Retail',
 'Tea (green) - Retail',
 'Peas (yellow) - Retail',
 'Fuel (diesel) - Retail',
 'Fuel (petrol-gasoline) - Retail',
 'Beans (kidney white) - Retail',
 'Meat (buffalo, first quality) - Retail',
 'Meat (buffalo, second quality) - Retail',
 'Rice (glutinous, first quality) - Retail',
 'Rice (glutinous, second quality) - Retail',
 'Rice (ordinary, first quality) - Retail',
 'Rice (ordinary, second quality) - Retail',
 'Rice (ordinary, unmilled) - Retail',
 'Sugar (brown) - Retail',
 'Garlic (small) - Retail',
 'Fish (tilapia, farmed) - Retail',
 'Rice (imported, Egyptian) - Retail',
 'Bulgur (brown) - Retail',
 'Meat (chicken, whole, frozen) - Retail',
 'Lentils (green) - Retail',
 'Lentils (red) - Retail',
 'Lentils (brown) - Retail',
 'Chili (green) - Retail',
 'Milk (powder, infant formula) - Retail',
 'Laundry soap - Retail',
 'Couscous - Retail',
 'Rice (paddy) - Producer',
 'Cassava (dry) - Retail',
 'Maize (crushed) - Retail',
 'Pigeon peas - Retail',
 'Sorghum (taghalit) - Retail',
 'Wheat meal - Retail',
 "Sorghum (r'haya) - Retail",
 'Tortilla - Retail',
 'Beans (black, Veracruz) - Wholesale',
 'Beans (black, Zacatecas) - Wholesale',
 'Rice (long grain, Sinaloa) - Wholesale',
 'Rice (small grain, Morelos) - Wholesale',
 'Beans (black, Nayarit) - Wholesale',
 'Wheat flour (local) - Retail',
 'Maize meal (white, first grade) - Retail',
 'Sugar (brown, imported) - Retail',
 'Sugar (brown, local) - Retail',
 'Maize meal (white, with bran) - Retail',
 'Garlic (large) - Retail',
 'Potatoes (Irish, imported) - Retail',
 'Potatoes (Irish, local) - Retail',
 'Groundnuts (Mix) - Retail',
 'Beans (butter) - Retail',
 'Beans (magnum) - Retail',
 'Groundnuts (large, shelled) - Retail',
 'Beans (catarino) - Retail',
 'Maize meal (white, without bran) - Retail',
 'Groundnuts (small, shelled) - Retail',
 'Beans (fresh) - Retail',
 'Potatoes (unica) - Retail',
 'Chickpeas (local) - Retail',
 'Rice (Emata) - Wholesale',
 'Lentils (broken) - Retail',
 'Potatoes (red) - Retail',
 'Cowpeas (white) - Retail',
 'Cowpeas (brown) - Retail',
 'Sorghum (brown) - Retail',
 'Cassava meal (gari, yellow) - Retail',
 'Gari (white) - Retail',
 'Yam (Abuja) - Retail',
 'Poultry - Retail',
 'Beans(mash) - Retail',
 'Cassava flour - Wholesale',
 'Rice (regular, milled) - Wholesale',
 'Rice (regular, milled) - Retail',
 'Wheat flour (locally processed) - Retail',
 'Rice (milled, superior) - Wholesale',
 'Rice (milled, superior) - Retail',
 'Beans (mung) - Retail',
 'Beans (string) - Retail',
 'Coconut - Retail',
 'Ginger - Retail',
 'Fish (milkfish) - Retail',
 'Fish (roundscad) - Retail',
 'Bitter melon - Retail',
 'Cabbage (chinese) - Retail',
 'Bananas (lakatan) - Retail',
 'Bananas (latundan) - Retail',
 'Calamansi - Retail',
 'Mangoes (carabao) - Retail',
 'Choko - Retail',
 'Bottle gourd - Retail',
 'Sweet Potato leaves - Retail',
 'Bananas (saba) - Retail',
 'Meat (pork, with bones) - Retail',
 'Meat (pork, hock) - Retail',
 'Fish (redbelly yellowtail fusilier) - Retail',
 'Shrimp (endeavor) - Retail',
 'Shrimp (tiger) - Retail',
 'Fish (frigate tuna) - Retail',
 'Rice (well milled) - Retail',
 'Pineapples - Retail',
 'Mandarins - Retail',
 'Semolina (yellow) - Retail',
 'Mangoes (piko) - Retail',
 'Rice (premium) - Retail',
 'Rice (special) - Retail',
 'Anchovies - Retail',
 'Fish (threadfin bream) - Retail',
 'Crab - Retail',
 'Fish (slipmouth) - Retail',
 'Sweet potatoes - Wholesale',
 'Fish (fresh) - Wholesale',
 'Maize flour (yellow) - Retail',
 'Rice (paddy) - Farm Gate',
 'Semolina (white) - Retail',
 'Maize flour (white) - Wholesale',
 'Maize flour (white) - Retail',
 'Maize flour (yellow) - Wholesale',
 'Wheat flour (high grade) - Wholesale',
 'Cauliflower - Retail',
 'Sorghum flour - Retail',
 'Passion fruit - Retail',
 'Zucchini - Retail',
 'Peas (fresh) - Retail',
 'Peas (dry) - Retail',
 'Rice (long grain, high quality, local) - Retail',
 'Sorghum (imported) - Retail',
 'Beans (fava) - Retail',
 'Fish (herring) - Retail',
 'Potato Leaves - Retail',
 'Okra (dry) - Retail',
 'Peas (yellow, split, food aid) - Retail',
 'Wage (non-qualified labour, non-agricultural) - Retail',
 'Millet (white) - Retail',
 'Rice (red nadu) - Retail',
 'Chili (red, dry raw) - Wholesale',
 'Onions (red, local) - Wholesale',
 'Onions (red, local) - Retail',
 'Onions (red, imported) - Wholesale',
 'Onions (red, imported) - Retail',
 'Potatoes (local) - Wholesale',
 'Potatoes (local) - Retail',
 'Potatoes (imported) - Wholesale',
 'Potatoes (imported) - Retail',
 'Rice (medium grain) - Wholesale',
 'Rice (red nadu) - Wholesale',
 'Onions (imported) - Wholesale',
 'Rice (red) - Wholesale',
 'Fish (dry, katta) - Wholesale',
 'Fish (dry, katta) - Retail',
 'Fish (dry, sprats) - Wholesale',
 'Fish (dry, sprats) - Retail',
 'Fish (yellowfin tuna) - Wholesale',
 'Fish (yellowfin tuna) - Retail',
 'Fish (sail fish) - Wholesale',
 'Fish (sail fish) - Retail',
 'Fish (skipjack tuna) - Wholesale',
 'Fish (skipjack tuna) - Retail',
 'Fish (jack) - Wholesale',
 'Fish (jack) - Retail',
 'Fish (goldstripe sardinella) - Wholesale',
 'Fish (trenched sardinella) - Wholesale',
 'Fish (trenched sardinella) - Retail',
 'Bananas (medium size) - Retail',
 'Fish (red snapper) - Retail',
 'Onions (dry, local) - Retail',
 'Potatoes (medium size) - Retail',
 'Tomatoes (greenhouse) - Retail',
 'Cheese (goat) - Retail',
 'Rice (short grain, low quality, local) - Retail',
 'Milk (pasteurized) - Retail',
 'Beans (sugar) - Retail',
 'Meat (beef, minced) - Retail',
 'Meat (chicken, plucked) - Retail',
 'Labaneh - Retail',
 'Yogurt - Retail',
 'Yeast - Retail',
 'Meat (chicken, legs) - Retail',
 'Beans (kidney) - Retail',
 'Eggs (imported) - Retail',
 'Meat (chicken, imported) - Retail',
 'Rice (white, local) - Retail',
 'Bread (common) - Retail',
 'Meat (veal) - Retail',
 'Cocoa (powder) - Retail',
 'Curd - Retail',
 'Meat (mixed, sausage) - Retail',
 'Fat (salo) - Retail',
 'Meat (beef, with bones) - Retail',
 'Beans (green) - Retail',
 'Tomatoes (bitter) - Retail',
 'Beans (spotted) - Retail',
 'Beans (kidney red) - Retail',
 'Peas (yellow, split) - Retail',
 'Cassava meal - Retail',
 'Maize meal (white, roller) - Retail',
 'Maize meal (white, breakfast) - Retail',
 'Wheat flour (fortified) - Retail',
 'Sugar (white, fortified) - Retail',
 'Beans (sugar, biofortified) - Retail',
 'Maize meal (white, fortified) - Retail',
 'Maize (yellow, biofortified) - Retail',
 'Sorghum (biofortified) - Retail',
 'Millet (biofortified) - Retail']

In [19]:
len(b)

829

In [10]:
c = df['adm0_name'].unique()

In [18]:
len(c)

98

In [41]:
d = df['mp_year'].unique()

In [42]:
d

array([2014, 2015, 2016, 2017, 2018, 2019, 2020, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2000, 2001, 2002, 1996,
       1997, 1998, 1999, 1994, 1995, 1992, 1993, 1990, 1991])